import './globals.css'
import { Montserrat } from 'next/font/google'

const inter = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} font-mont bg-light w-full min-h-screen `}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
